### ISSUE TITLE
Kysely migrate fails in a read-only file system

### ISSUE THREAD

**Issue by shoooe** [kysely-org/kysely-ctl#103]
**Info**

Using `kysely-ctl` v0.9.0.

**Issue**

I'm trying to run `kysely migrate` on a deploy command in a read-only file system environment (it's the Digital Ocean PaaS).
I'm getting this error:

> [2024-08-30 13:11:37] $ kysely migrate latest
[2024-08-30 13:11:39] 
[2024-08-30 13:11:39]  ERROR  Permission denied
[2024-08-30 13:11:39] 
[2024-08-30 13:11:39]   at writeFileSync (native)
[2024-08-30 13:11:39]   at <anonymous> (node_modules/jiti/dist/jiti.js:1:242785)
[2024-08-30 13:11:39]   at transform (node_modules/jiti/dist/jiti.js:1:242836)
[2024-08-30 13:11:39]   at evalModule (node_modules/jiti/dist/jiti.js:1:246227)
[2024-08-30 13:11:39]   at jiti (node_modules/jiti/dist/jiti.js:1:245240)
[2024-08-30 13:11:39]   at <anonymous> (node_modules/c12/dist/shared/c12.cab0c9da.mjs:345:26)
[2024-08-30 13:11:39]   at resolveConfig (node_modules/c12/dist/shared/c12.cab0c9da.mjs:279:30)
[2024-08-30 13:11:39]   at <anonymous> (node_modules/c12/dist/shared/c12.cab0c9da.mjs:147:29)
[2024-08-30 13:11:39]   at processTicksAndRejections (unknown:12:39) 
[2024-08-30 13:11:39] 
[2024-08-30 13:11:39] 
[2024-08-30 13:11:39] 
[2024-08-30 13:11:39]  ERROR  Permission denied
[2024-08-30 13:11:39] 
[2024-08-30 13:11:39] error: script "migrate" exited with code 1
[2024-08-30 13:11:39] error: script "start" exited with code 1

Since I'm just trying to run migrations why is the CLI calling `writeFileSync`? What is it trying to write?
What am I doing wrong?

Thanks ❤️

**Comment by igalklebanov** [comment]
Hey 👋 

This seems to be a default `jiti` [behavior](https://github.com/unjs/jiti#fscache).

For now, you can turn it off with `JITI_FS_CACHE=false kysely migrate latest`

**Comment by igalklebanov** [comment]
This behavior can also be disabled using the `--no-filesystem-caching` flag in https://github.com/kysely-org/kysely-ctl/releases/tag/v0.10.1.
