### ISSUE TITLE
Importing file with alias path is not working

### ISSUE THREAD

**Issue by JeromeDeLeon** [kysely-org/kysely-ctl#109]
# Description

Currently, the `kysely.config.ts` file is importing the `kysely` instance I created on a separate file and the path is an alias path like `@/path/to/kysely`.

This throws an error on the CLI.

Looking at `c12`, it looks like it's exposing [`jitiOptions`](https://github.com/unjs/c12?tab=readme-ov-file#jitioptions) which also exposes the [`alias`](https://github.com/unjs/jiti?tab=readme-ov-file#alias) to allow alias path.

```
ERROR  Cannot find module '@/path/to/kysely'
Require stack:
- /repo/kysely.config.ts

  Require stack:
  - kysely.config.ts
  at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
  at Function.resolve (node:internal/modules/helpers:190:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:241814)
  at jiti (node_modules/jiti/dist/jiti.js:1:244531)
  at kysely.config.ts:2:15
  at evalModule (node_modules/jiti/dist/jiti.js:1:247313)
  at Object.jiti (node_modules/jiti/dist/jiti.js:1:245241)
  at resolveConfig (node_modules/c12/dist/shared/c12.cab0c9da.mjs:345:26)
  at loadConfig (node_modules/c12/dist/shared/c12.cab0c9da.mjs:147:29)
  at async getConfig (node_modules/kysely-ctl/dist/bin.js:226:24)
```

# Workaround

Manually configure using `dialect` and `dialectConfig` essentially repeating the same logic.

# Package Info

```
kysely v0.27.4
kysely-ctl v0.9.0
```

**Comment by JeromeDeLeon** [comment]
Another workaround is to use `jiti` inside the config and move `.env.local` to `.env` for `Next.js` application

```ts
import { fileURLToPath } from 'url';
import createJiti from 'jiti';
import { defineConfig } from 'kysely-ctl';

const moduleFileUrl = import.meta.url;

const jiti = createJiti(fileURLToPath(moduleFileUrl), {
  // Since `jiti` uses isolated environment, we need to provide an alias for the src directory
  // See: https://github.com/unjs/jiti/issues/104
  alias: { '@': fileURLToPath(new URL('./src', moduleFileUrl)) },
});

const kysely = jiti('./src/path/to/kysely.ts');

export default defineConfig({
  kysely,
  // other kysely-ctl config
});
```

**Comment by gvanderclay** [comment]
I encountered the same issue. Luckily @JeromeDeLeon's workaround works!

**Comment by igalklebanov** [comment]
Hey @JeromeDeLeon 👋 

Thanks for raising this and coming up with a workaround! 💪 

`jiti` does not automatically infer aliases from `tsconfig` or other sources [by design](https://github.com/unjs/jiti/issues/166#issuecomment-2374322954).

Where are you configuring your aliases?

**Comment by JeromeDeLeon** [comment]
We're relying on `tsconfig` for this one.

**Comment by AssisrMatheus** [comment]
> Another workaround is to use `jiti` inside the config and move `.env.local` to `.env` for `Next.js` application
> 
> ```ts
> import { fileURLToPath } from 'url';
> import createJiti from 'jiti';
> import { defineConfig } from 'kysely-ctl';
> 
> const moduleFileUrl = import.meta.url;
> 
> const jiti = createJiti(fileURLToPath(moduleFileUrl), {
>   // Since `jiti` uses isolated environment, we need to provide an alias for the src directory
>   // See: https://github.com/unjs/jiti/issues/104
>   alias: { '@': fileURLToPath(new URL('./src', moduleFileUrl)) },
> });
> 
> const kysely = jiti('./src/path/to/kysely.ts');
> 
> export default defineConfig({
>   kysely,
>   // other kysely-ctl config
> });
> ```

Do you know why we have to move `.env.local` to `.env` even if we do
```ts
import { loadEnvConfig } from '@next/env';
loadEnvConfig(process.cwd());
```

regardless?

**Comment by igalklebanov** [comment]
Check https://github.com/kysely-org/kysely-ctl/releases/tag/v0.11.0. Lemme know if there are any issues.

**Comment by rebasecase** [comment]
I am relatively new to the modern js ecosystem, I am really enjoying using it. It doesn’t seem to “get in the way” like the big players react flavours/vue etc.. It was all very overwhelming for me. 

This is why I started to use Kysely - it just does what you ask it to with zero ceremony. Really fantastic. Thank you!

**Comment by igalklebanov** [comment]
No problem!

BTW, try https://github.com/kysely-org/kysely-ctl/releases/tag/v0.15.0. I added a test that mimics the Svelte setup in CI to verify.

**Comment by rebasecase** [comment]
Hmm same issue. N.B. This is when importing (and calling) a function from an aliased path. Importing types works correctly though. I don't know enough about this really. 

```
"kysely-ctl": "^0.15.1",
"kysely": "^0.28.4",
```

https://stackblitz.com/edit/sveltejs-kit-template-default-rpqfn5qp?file=src%2Fkysely.config.ts

If you create a new terminal `cd src && kysely migrate list` (or any other command that tries to load the config) it will exhibit the behaviour above

this doesn't want to resolve aliases from the root directory, so I put kysely.config.ts under src (This will be a sveltekit configuration that I am unsure how to fix)

**Comment by igalklebanov** [comment]
You need to use the `--experimental-resolve-tsconfig-paths` flag.
